version: "3"

services:

    companyweb:
      container_name: companyweb
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - ${PORT}:${PORT}
      volumes:
        - ./:/src/server/app
        - /src/server/app/node_modules
      working_dir: /src/server/app
      env_file:
        - ./.env
      depends_on:
        - companywebdb
        
    companywebdb:
      image: postgres:13-alpine
      restart: always
      env_file:
        - ./.env
      environment:
        HOST: 0.0.0.0
      ports:
        - ${POSTGRES_PORT}:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
